#pragma once

enum clguiObjectType {
  OBJECT_TYPE_BUTTON = 0,
  OBJECT_TYPE_SLIDER,
  OBJECT_TYPE_LABEL,
  OBJECT_TYPE_CHECKBOX,
  OBJECT_TYPE_WINDOW,
  OBJECT_TYPE_MENUBAR,
  OBJECT_TYPE_MENU,
  OBJECT_TYPE_MENUITEM,
  OBJECT_TYPE_NULL,
};
