#ifndef DEBUG_H_INCLUDED
#define DEBUG_H_INCLUDED

#include <windows.h>
#include <string>
#include <vector>
#include "clTypes.h"

namespace ConsoleForeground{
enum{
  BLACK=0,
  DARKBLUE=FOREGROUND_BLUE,
  DARKGREEN=FOREGROUND_GREEN,
  DARKCYAN=FOREGROUND_GREEN|FOREGROUND_BLUE,
  DARKRED=FOREGROUND_RED,
  DARKMAGENTA=FOREGROUND_RED|FOREGROUND_BLUE,
  DARKYELLOW=FOREGROUND_RED|FOREGROUND_GREEN,
  DARKGRAY=FOREGROUND_RED|FOREGROUND_GREEN|FOREGROUND_BLUE,
  GRAY=FOREGROUND_INTENSITY,
  BLUE=FOREGROUND_INTENSITY|FOREGROUND_BLUE,
  GREEN=FOREGROUND_INTENSITY|FOREGROUND_GREEN,
  CYAN=FOREGROUND_INTENSITY|FOREGROUND_GREEN|FOREGROUND_BLUE,
  RED=FOREGROUND_INTENSITY|FOREGROUND_RED,
  MAGENTA=FOREGROUND_INTENSITY|FOREGROUND_RED|FOREGROUND_BLUE,
  YELLOW=FOREGROUND_INTENSITY|FOREGROUND_RED|FOREGROUND_GREEN,
  WHITE=FOREGROUND_INTENSITY|FOREGROUND_RED|FOREGROUND_GREEN|FOREGROUND_BLUE,
};
}

namespace cl{
void Text(const clString& s,int color=ConsoleForeground::WHITE);
void HighLightText(const clString& s,clI color,std::vector<clUi>& pos,clI posColor);
void Unimportant(const clString& s,clB newLine=true);
void Info(const clString& s,clB newLine=true);
void Warning(const clString& s,clB newLine=true);
void Error(const clString& s,clB newLine=true);
}

#endif // DEBUG_H_INCLUDED
